# models dir
data_dir: "/hpc/compgen/projects/nanoxog/babe/analysis/mpages/train_input"
model_dir: "/hpc/compgen/projects/nanoxog/babe/analysis/mpages/models/grid_recurrent"

# Train configuration
cnn_type: ["bonito"]
encoder_type: ["shallow"] # ["shallow", 'deep']
decoder_type: ["shallow"] # ["shallow", 'deep']
attention_type: ['None', 'dot'] # ['None', 'dot', 'general', 'concat']
attention_pos: ['upstream', 'downstream'] # ['upstream', 'downstream']
monotonic: '' # put zero length string if not ["--monotonic", ""]
window_size: [400]
task: ["human"] 
batch_size: 64
use_scaler: [""] # put zero length string if not ["--use-scaler", ""]
overwrite: '--overwrite' # put zero length string if not ["--overwrite", ""]

# Basecall configuration
window_overlap: [400]
file_list: '/hpc/compgen/users/mpages/babe/doc/splits/human_task_test_reads.txt'
beam_size: [1]
beam_threshold: 0.1
buffer_size: 1

# Evaluate configuration
references_path: '/hpc/compgen/projects/nanoxog/raw/benchmark/all_read_references.fasta'
processes: 32
